#!/usr/bin/env bash
# Install Caddy reverse proxy with automatic HTTPS for broker + dashboard.
# Requires a public DNS A record pointing at this VPS.
#
# Usage:
#   export SF4E_BROKER_DOMAIN=netplay.example.com
#   bash install-caddy.sh
#
# Optional separate dashboard host:
#   export SF4E_DASHBOARD_DOMAIN=admin.example.com
set -euo pipefail

BROKER_DIR="${BROKER_DIR:-/root/room-broker}"
DOMAIN="${SF4E_BROKER_DOMAIN:-}"
DASHBOARD_DOMAIN="${SF4E_DASHBOARD_DOMAIN:-}"
CADDYFILE="/etc/caddy/Caddyfile"

if [[ -z "$DOMAIN" ]]; then
  echo "Set SF4E_BROKER_DOMAIN to your public hostname (DNS A record -> this VPS)."
  exit 1
fi

if ! command -v caddy >/dev/null 2>&1; then
  apt-get update -qq
  apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
  apt-get install -y caddy
fi

GLOBAL_BLOCK=""
if [[ -n "${SF4E_ACME_EMAIL:-}" ]]; then
  GLOBAL_BLOCK="# SF4e — auto-generated by install-caddy.sh
{
	email ${SF4E_ACME_EMAIL}
}
"
else
  GLOBAL_BLOCK="# SF4e — auto-generated by install-caddy.sh
"
fi

if [[ -n "$DASHBOARD_DOMAIN" && "$DASHBOARD_DOMAIN" != "$DOMAIN" ]]; then
  cat > "$CADDYFILE" <<EOF
${GLOBAL_BLOCK}
${DOMAIN} {
	encode gzip zstd

	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "strict-origin-when-cross-origin"
		-Server
	}

	handle /v1/* {
		reverse_proxy 127.0.0.1:8787 {
			header_up X-Forwarded-For {remote_host}
			header_up X-Forwarded-Proto {scheme}
			header_up Host {host}
		}
	}

	respond / "SF4e broker API — use /v1/* endpoints." 404
}

${DASHBOARD_DOMAIN} {
	encode gzip zstd

	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "strict-origin-when-cross-origin"
		-Server
	}

	reverse_proxy 127.0.0.1:8789 {
		header_up X-Forwarded-For {remote_host}
		header_up X-Forwarded-Proto {scheme}
		header_up Host {host}
	}
}
EOF
else
  cat > "$CADDYFILE" <<EOF
${GLOBAL_BLOCK}
${DOMAIN} {
	encode gzip zstd

	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "strict-origin-when-cross-origin"
		-Server
	}

	handle /v1/* {
		reverse_proxy 127.0.0.1:8787 {
			header_up X-Forwarded-For {remote_host}
			header_up X-Forwarded-Proto {scheme}
			header_up Host {host}
		}
	}

	handle {
		reverse_proxy 127.0.0.1:8789 {
			header_up X-Forwarded-For {remote_host}
			header_up X-Forwarded-Proto {scheme}
			header_up Host {host}
		}
	}
}
EOF
fi

# Broker + dashboard on localhost only
grep -q '^BROKER_BIND=' "$BROKER_DIR/.env" 2>/dev/null && \
  sed -i 's|^BROKER_BIND=.*|BROKER_BIND=127.0.0.1|' "$BROKER_DIR/.env" || \
  echo "BROKER_BIND=127.0.0.1" >> "$BROKER_DIR/.env"
grep -q '^BROKER_TRUST_PROXY=' "$BROKER_DIR/.env" 2>/dev/null && \
  sed -i 's|^BROKER_TRUST_PROXY=.*|BROKER_TRUST_PROXY=1|' "$BROKER_DIR/.env" || \
  echo "BROKER_TRUST_PROXY=1" >> "$BROKER_DIR/.env"
grep -q '^BROKER_PUBLIC_URL=' "$BROKER_DIR/.env" 2>/dev/null && \
  sed -i "s|^BROKER_PUBLIC_URL=.*|BROKER_PUBLIC_URL=https://${DOMAIN}|" "$BROKER_DIR/.env" || \
  echo "BROKER_PUBLIC_URL=https://${DOMAIN}" >> "$BROKER_DIR/.env"

DASHBOARD_ENV="/opt/sf4e-relay/dashboard/.env"
if [[ -f "$DASHBOARD_ENV" ]]; then
  grep -q '^DASHBOARD_BIND=' "$DASHBOARD_ENV" && \
    sed -i 's|^DASHBOARD_BIND=.*|DASHBOARD_BIND=127.0.0.1|' "$DASHBOARD_ENV" || \
    echo "DASHBOARD_BIND=127.0.0.1" >> "$DASHBOARD_ENV"
  grep -q '^COOKIE_SECURE=' "$DASHBOARD_ENV" && \
    sed -i 's|^COOKIE_SECURE=.*|COOKIE_SECURE=1|' "$DASHBOARD_ENV" || \
    echo "COOKIE_SECURE=1" >> "$DASHBOARD_ENV"
  systemctl restart sf4e-relay-dashboard.service 2>/dev/null || true
fi

systemctl enable caddy
systemctl reload caddy || systemctl restart caddy
systemctl restart sf4e-broker.service 2>/dev/null || true

if [[ -x "$BROKER_DIR/secure-ufw.sh" ]]; then
  bash "$BROKER_DIR/secure-ufw.sh"
fi

echo "Caddy installed. Broker API: https://${DOMAIN}/v1/health"
if [[ -n "$DASHBOARD_DOMAIN" && "$DASHBOARD_DOMAIN" != "$DOMAIN" ]]; then
  echo "Dashboard: https://${DASHBOARD_DOMAIN}/login"
else
  echo "Dashboard: https://${DOMAIN}/login"
fi
echo "Set launcher broker URL: https://${DOMAIN}"
